version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_DATABASE: dev
      REDIS_URL: redis://redis:6378
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo
    container_name: mongodb
    env_file: ./.env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - mongodb:/data/db
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  mongodb:
    driver: local
